name: oxvpn
description: OxVPN — fast, private, ad-free VPN.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  openvpn_flutter: ^1.3.3
  dio: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_servers.json
